package source;

import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dungx
 */
public class DictionaryApplication extends javax.swing.JFrame {
DictionaryManagement dicM = new DictionaryManagement();
    /**
     * Creates new form Home_Frame
     */
    public DictionaryApplication() {
        dicM.insertFromJDBC();
        initComponents();       
        menu_tab1.setBackground(new Color(255,255,153));
        tab1.setVisible(true);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        add_submit_button = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        add_explain_textarea = new javax.swing.JTextArea();
        add_target_teaxfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        message_dialog = new javax.swing.JDialog();
        message_panel = new javax.swing.JPanel();
        message_ok_button = new javax.swing.JButton();
        message_lable = new javax.swing.JLabel();
        edit_dialog = new javax.swing.JDialog();
        edit_panel = new javax.swing.JPanel();
        edit_submit_button = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        edit_explain_textarea = new javax.swing.JTextArea();
        edit_target_teaxfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        menuTab = new javax.swing.JPanel();
        menu_tab1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menu_tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menu_tab3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menu_tab4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        content = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        tab1_target_textField = new javax.swing.JTextField();
        tab1_translate_button = new javax.swing.JButton();
        tab1_speak_button = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tab1_suggest_list = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        tab1_explain_textArea = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        tab2_target_textField = new javax.swing.JTextField();
        tab2_translate_button = new javax.swing.JButton();
        tab2_add_button = new javax.swing.JButton();
        tab2_edit_button = new javax.swing.JButton();
        tab2_delete_button = new javax.swing.JButton();
        tab2_speak_button = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tab2_suggest_list = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        tab2_explain_textArea = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        tab3_translate_button = new javax.swing.JButton();
        tab3_selected = new javax.swing.JComboBox<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        tab3_target_textArea = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        tab3_explain_textArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();

        add_dialog.setTitle("Add Word");
        add_dialog.setAlwaysOnTop(true);
        add_dialog.setBackground(new java.awt.Color(153, 153, 255));
        add_dialog.setMinimumSize(new java.awt.Dimension(607, 400));
        add_dialog.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        add_submit_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_submit_button.setText("Submit");
        add_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_submit_buttonActionPerformed(evt);
            }
        });

        add_explain_textarea.setColumns(20);
        add_explain_textarea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_explain_textarea.setRows(5);
        jScrollPane13.setViewportView(add_explain_textarea);

        add_target_teaxfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("New word's target");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("New word's explain");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(add_target_teaxfield))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(add_submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_target_teaxfield, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        message_dialog.setTitle("Message");
        message_dialog.setMinimumSize(new java.awt.Dimension(300, 200));
        message_dialog.setResizable(false);
        message_dialog.setSize(new java.awt.Dimension(300, 200));

        message_panel.setBackground(new java.awt.Color(255, 153, 153));
        message_panel.setMaximumSize(new java.awt.Dimension(200, 200));
        message_panel.setMinimumSize(new java.awt.Dimension(300, 200));
        message_panel.setPreferredSize(new java.awt.Dimension(300, 200));
        message_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message_ok_button.setBackground(new java.awt.Color(255, 102, 102));
        message_ok_button.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        message_ok_button.setText("OK");
        message_ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                message_ok_buttonActionPerformed(evt);
            }
        });
        message_panel.add(message_ok_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        message_lable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        message_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message_lable.setText("Done!");
        message_panel.add(message_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 50, 290, -1));

        javax.swing.GroupLayout message_dialogLayout = new javax.swing.GroupLayout(message_dialog.getContentPane());
        message_dialog.getContentPane().setLayout(message_dialogLayout);
        message_dialogLayout.setHorizontalGroup(
            message_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(message_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        message_dialogLayout.setVerticalGroup(
            message_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(message_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        edit_dialog.setTitle("Edit word");
        edit_dialog.setAlwaysOnTop(true);
        edit_dialog.setBackground(new java.awt.Color(153, 153, 255));
        edit_dialog.setMinimumSize(new java.awt.Dimension(607, 400));
        edit_dialog.setResizable(false);

        edit_panel.setBackground(new java.awt.Color(255, 204, 204));

        edit_submit_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edit_submit_button.setText("Submit");
        edit_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_submit_buttonActionPerformed(evt);
            }
        });

        edit_explain_textarea.setColumns(20);
        edit_explain_textarea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edit_explain_textarea.setRows(5);
        jScrollPane14.setViewportView(edit_explain_textarea);

        edit_target_teaxfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("New word's target");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("New word's explain");

        javax.swing.GroupLayout edit_panelLayout = new javax.swing.GroupLayout(edit_panel);
        edit_panel.setLayout(edit_panelLayout);
        edit_panelLayout.setHorizontalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_panelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(edit_target_teaxfield))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_panelLayout.createSequentialGroup()
                        .addComponent(edit_submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        edit_panelLayout.setVerticalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_target_teaxfield, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit_submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout edit_dialogLayout = new javax.swing.GroupLayout(edit_dialog.getContentPane());
        edit_dialog.getContentPane().setLayout(edit_dialogLayout);
        edit_dialogLayout.setHorizontalGroup(
            edit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(edit_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        edit_dialogLayout.setVerticalGroup(
            edit_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_dialogLayout.createSequentialGroup()
                .addComponent(edit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuTab.setBackground(new java.awt.Color(102, 102, 255));

        menu_tab1.setBackground(new java.awt.Color(102, 0, 204));
        menu_tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_tab1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search");

        javax.swing.GroupLayout menu_tab1Layout = new javax.swing.GroupLayout(menu_tab1);
        menu_tab1.setLayout(menu_tab1Layout);
        menu_tab1Layout.setHorizontalGroup(
            menu_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_tab1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_tab1Layout.setVerticalGroup(
            menu_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_tab1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menu_tab2.setBackground(new java.awt.Color(102, 0, 204));
        menu_tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edit dictionary");

        javax.swing.GroupLayout menu_tab2Layout = new javax.swing.GroupLayout(menu_tab2);
        menu_tab2.setLayout(menu_tab2Layout);
        menu_tab2Layout.setHorizontalGroup(
            menu_tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_tab2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_tab2Layout.setVerticalGroup(
            menu_tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_tab2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menu_tab3.setBackground(new java.awt.Color(102, 0, 204));
        menu_tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_tab3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Paragrap");

        javax.swing.GroupLayout menu_tab3Layout = new javax.swing.GroupLayout(menu_tab3);
        menu_tab3.setLayout(menu_tab3Layout);
        menu_tab3Layout.setHorizontalGroup(
            menu_tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_tab3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_tab3Layout.setVerticalGroup(
            menu_tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_tab3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menu_tab4.setBackground(new java.awt.Color(102, 0, 204));
        menu_tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_tab4MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("About us");

        javax.swing.GroupLayout menu_tab4Layout = new javax.swing.GroupLayout(menu_tab4);
        menu_tab4.setLayout(menu_tab4Layout);
        menu_tab4Layout.setHorizontalGroup(
            menu_tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_tab4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_tab4Layout.setVerticalGroup(
            menu_tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_tab4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dictionary");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout menuTabLayout = new javax.swing.GroupLayout(menuTab);
        menuTab.setLayout(menuTabLayout);
        menuTabLayout.setHorizontalGroup(
            menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuTabLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        menuTabLayout.setVerticalGroup(
            menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTabLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(menu_tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        tab1.setBackground(new java.awt.Color(255, 255, 153));
        tab1.setPreferredSize(new java.awt.Dimension(815, 600));

        tab1_target_textField.setBackground(new java.awt.Color(255, 255, 204));
        tab1_target_textField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab1_target_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1_target_textFieldActionPerformed(evt);
            }
        });
        tab1_target_textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tab1_target_textFieldKeyReleased(evt);
            }
        });

        tab1_translate_button.setBackground(new java.awt.Color(255, 204, 102));
        tab1_translate_button.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tab1_translate_button.setText("Search");
        tab1_translate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1_translate_buttonActionPerformed(evt);
            }
        });

        tab1_speak_button.setBackground(new java.awt.Color(255, 204, 102));
        tab1_speak_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tab1_speak_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/speak.png"))); // NOI18N
        tab1_speak_button.setText("Speak");
        tab1_speak_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1_speak_buttonActionPerformed(evt);
            }
        });

        tab1_suggest_list.setBackground(new java.awt.Color(255, 255, 204));
        tab1_suggest_list.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab1_suggest_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1_suggest_listMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tab1_suggest_list);

        tab1_explain_textArea.setBackground(new java.awt.Color(255, 255, 204));
        tab1_explain_textArea.setColumns(20);
        tab1_explain_textArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab1_explain_textArea.setRows(5);
        jScrollPane8.setViewportView(tab1_explain_textArea);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/meohoc2.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("MV Boli", 2, 48)); // NOI18N
        jLabel17.setText("Dictionary searcher");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/meohocbai.png"))); // NOI18N

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tab1Layout.createSequentialGroup()
                                .addComponent(tab1_target_textField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tab1_translate_button)
                                .addGap(18, 18, 18)
                                .addComponent(tab1_speak_button))
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(29, 29, 29))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tab1_target_textField)
                    .addComponent(tab1_speak_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab1_translate_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab2.setBackground(new java.awt.Color(255, 153, 153));

        tab2_target_textField.setBackground(new java.awt.Color(255, 204, 204));
        tab2_target_textField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab2_target_textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tab2_target_textFieldKeyReleased(evt);
            }
        });

        tab2_translate_button.setBackground(new java.awt.Color(255, 102, 102));
        tab2_translate_button.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tab2_translate_button.setText("Search");
        tab2_translate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2_translate_buttonActionPerformed(evt);
            }
        });

        tab2_add_button.setBackground(new java.awt.Color(255, 102, 102));
        tab2_add_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tab2_add_button.setText("Add");
        tab2_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2_add_buttonActionPerformed(evt);
            }
        });

        tab2_edit_button.setBackground(new java.awt.Color(255, 102, 102));
        tab2_edit_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tab2_edit_button.setText("Edit");
        tab2_edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2_edit_buttonActionPerformed(evt);
            }
        });

        tab2_delete_button.setBackground(new java.awt.Color(255, 102, 102));
        tab2_delete_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tab2_delete_button.setText("Delete");
        tab2_delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2_delete_buttonActionPerformed(evt);
            }
        });

        tab2_speak_button.setBackground(new java.awt.Color(255, 102, 102));
        tab2_speak_button.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tab2_speak_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/speak.png"))); // NOI18N
        tab2_speak_button.setText("Speak");
        tab2_speak_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2_speak_buttonActionPerformed(evt);
            }
        });

        tab2_suggest_list.setBackground(new java.awt.Color(255, 204, 204));
        tab2_suggest_list.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab2_suggest_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2_suggest_listMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tab2_suggest_list);

        tab2_explain_textArea.setBackground(new java.awt.Color(255, 204, 204));
        tab2_explain_textArea.setColumns(20);
        tab2_explain_textArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab2_explain_textArea.setRows(5);
        jScrollPane10.setViewportView(tab2_explain_textArea);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/commeo.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MEOFA.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("MV Boli", 2, 36)); // NOI18N
        jLabel21.setText("Edit dictionary");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                        .addComponent(tab2_target_textField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tab2_translate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2_edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab2_delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab2_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tab2_speak_button)
                        .addGap(149, 149, 149))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(tab2_speak_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tab2_target_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tab2_translate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9))
                    .addComponent(jScrollPane10))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(tab2_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2_delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2_edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        tab3.setBackground(new java.awt.Color(255, 204, 255));

        tab3_translate_button.setBackground(new java.awt.Color(0, 51, 204));
        tab3_translate_button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tab3_translate_button.setForeground(new java.awt.Color(255, 255, 255));
        tab3_translate_button.setText("Translate");
        tab3_translate_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tab3_translate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3_translate_buttonActionPerformed(evt);
            }
        });

        tab3_selected.setBackground(new java.awt.Color(0, 51, 204));
        tab3_selected.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tab3_selected.setForeground(new java.awt.Color(255, 255, 255));
        tab3_selected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English to Vietnamese", "Vietnamese to English" }));

        tab3_target_textArea.setColumns(20);
        tab3_target_textArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab3_target_textArea.setRows(5);
        jScrollPane11.setViewportView(tab3_target_textArea);

        tab3_explain_textArea.setColumns(20);
        tab3_explain_textArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab3_explain_textArea.setRows(5);
        jScrollPane12.setViewportView(tab3_explain_textArea);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Google_Translate_Icon.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/meo_kid.png"))); // NOI18N

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab3Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(tab3_translate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(283, 283, 283))
                    .addGroup(tab3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(tab3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(tab3_selected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                                .addComponent(tab3_selected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))
                    .addGroup(tab3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tab3_translate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tab4.setBackground(new java.awt.Color(204, 255, 204));
        tab4.setPreferredSize(new java.awt.Dimension(815, 600));
        tab4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/About_us.png"))); // NOI18N
        tab4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_tab1MouseClicked
        // TODO add your handling code here:
        tab1.setVisible(true);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(false);
        
        menu_tab1.setBackground(new Color(255,255,153));
        menu_tab2.setBackground(new Color(102,0,204));
        menu_tab3.setBackground(new Color(102,0,204));
        menu_tab4.setBackground(new Color(102,0,204));
        
        tab1_explain_textArea.setLineWrap(true);
        tab1_explain_textArea.setWrapStyleWord(true);        
    }//GEN-LAST:event_menu_tab1MouseClicked

    private void menu_tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_tab2MouseClicked
        tab1.setVisible(false);
        tab2.setVisible(true);
        tab3.setVisible(false);
        tab4.setVisible(false);
        
        menu_tab2.setBackground(new Color(255,153,153));
        menu_tab1.setBackground(new Color(102,0,204));
        menu_tab3.setBackground(new Color(102,0,204));
        menu_tab4.setBackground(new Color(102,0,204));
        
        tab2_explain_textArea.setLineWrap(true);
        tab2_explain_textArea.setWrapStyleWord(true);
    }//GEN-LAST:event_menu_tab2MouseClicked

    private void menu_tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_tab3MouseClicked
        //Hien thi tab
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(true);
        tab4.setVisible(false);
                
        menu_tab3.setBackground(new Color(255,204,255));
        menu_tab2.setBackground(new Color(102,0,204));
        menu_tab1.setBackground(new Color(102,0,204));
        menu_tab4.setBackground(new Color(102,0,204));
        
        tab3_target_textArea.setLineWrap(true);
        tab3_target_textArea.setWrapStyleWord(true);
        tab3_explain_textArea.setLineWrap(true);
        tab3_explain_textArea.setWrapStyleWord(true);
    }//GEN-LAST:event_menu_tab3MouseClicked

    private void menu_tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_tab4MouseClicked
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(true);
        
        menu_tab4.setBackground(new Color(204,255,204));
        menu_tab2.setBackground(new Color(102,0,204));
        menu_tab3.setBackground(new Color(102,0,204));
        menu_tab1.setBackground(new Color(102,0,204));
    }//GEN-LAST:event_menu_tab4MouseClicked

    private void tab2_translate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2_translate_buttonActionPerformed
        String search = tab2_target_textField.getText();          
        tab2_explain_textArea.setText(dicM.dictionaryLookup(search));        
        tab2_explain_textArea.setSelectionStart(0);
        tab2_explain_textArea.setSelectionEnd(0);
    }//GEN-LAST:event_tab2_translate_buttonActionPerformed

    private void tab3_translate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3_translate_buttonActionPerformed
        String selected = String.valueOf(tab3_selected.getSelectedItem());        
        //System.out.println(selected);
        if (selected == "English to Vietnamese") {
            tab3_target_textArea.setLineWrap(true);
            tab3_target_textArea.setWrapStyleWord(true);
            String targetString = tab3_target_textArea.getText();
            try {
                String explainString =  dicM.translate("en", "vi", targetString);
                tab3_explain_textArea.setText(explainString);
                //tu xuong dong
                tab3_explain_textArea.setLineWrap(true);
                tab3_explain_textArea.setWrapStyleWord(true);
            } catch (IOException ex) {
                Logger.getLogger(DictionaryApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        else {            
            String targetString = tab3_target_textArea.getText();
            try {
                String explainString =  dicM.translate("vi", "en", targetString);
                tab3_explain_textArea.setText(explainString);
            } catch (IOException ex) {
                Logger.getLogger(DictionaryApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tab3_translate_buttonActionPerformed

    private void tab1_target_textFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab1_target_textFieldKeyReleased
        String search = tab1_target_textField.getText();  
        
        DefaultListModel model = new DefaultListModel();
        ArrayList <Word> listSearch = new ArrayList<Word>();
        listSearch = dicM.dictionarySearcher(search);
        for (int i = 0; i < listSearch.size(); i++) {
            model.addElement(listSearch.get(i).getWord_target());
        }
        tab1_suggest_list.setModel(model);
        tab1_explain_textArea.setText("");
    }//GEN-LAST:event_tab1_target_textFieldKeyReleased

    private void tab1_translate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1_translate_buttonActionPerformed
        String search = tab1_target_textField.getText();          
        tab1_explain_textArea.setText(dicM.dictionaryLookup(search));
        tab1_explain_textArea.setSelectionStart(0);
        tab1_explain_textArea.setSelectionEnd(0);
    }//GEN-LAST:event_tab1_translate_buttonActionPerformed

    private void tab1_suggest_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1_suggest_listMouseClicked
        String search = tab1_suggest_list.getSelectedValue();
        tab1_target_textField.setText(search);
        tab1_explain_textArea.setText(dicM.dictionaryLookup(search));
        tab1_explain_textArea.setSelectionStart(0);
        tab1_explain_textArea.setSelectionEnd(0);
        //System.out.println(search);
    }//GEN-LAST:event_tab1_suggest_listMouseClicked

    private void tab1_speak_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1_speak_buttonActionPerformed
        String search = tab1_target_textField.getText();  
        VoiceManager voiceManager = VoiceManager.getInstance();
        com.sun.speech.freetts.Voice syntheticVoice = voiceManager.getVoice("kevin16");
        syntheticVoice.allocate();
        syntheticVoice.speak(search);
        syntheticVoice.deallocate();
    }//GEN-LAST:event_tab1_speak_buttonActionPerformed

    private void tab2_target_textFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab2_target_textFieldKeyReleased
        String search = tab2_target_textField.getText();          
        DefaultListModel model = new DefaultListModel();        
        ArrayList<Word> dic_searcher = new ArrayList<Word>();
        dic_searcher = dicM.dictionarySearcher(search);
        for (int i = 0; i < dic_searcher.size(); i++) {
            model.addElement(dic_searcher.get(i).getWord_target());
        }
        tab2_suggest_list.setModel(model);
        tab2_explain_textArea.setText("");
    }//GEN-LAST:event_tab2_target_textFieldKeyReleased

    private void tab2_suggest_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2_suggest_listMouseClicked
        String search = tab2_suggest_list.getSelectedValue();
        tab2_target_textField.setText(search);
        tab2_explain_textArea.setText(dicM.dictionaryLookup(search));
        tab2_explain_textArea.setSelectionStart(0);
        tab2_explain_textArea.setSelectionEnd(0);
    }//GEN-LAST:event_tab2_suggest_listMouseClicked

    private void tab2_speak_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2_speak_buttonActionPerformed
        String search = tab2_target_textField.getText();  
        VoiceManager voiceManager = VoiceManager.getInstance();
        com.sun.speech.freetts.Voice syntheticVoice = voiceManager.getVoice("kevin16");
        syntheticVoice.allocate();
        syntheticVoice.speak(search);
        syntheticVoice.deallocate();
    }//GEN-LAST:event_tab2_speak_buttonActionPerformed

    private void add_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_submit_buttonActionPerformed
        String new_target_String = add_target_teaxfield.getText();
        String new_explain_String = add_explain_textarea.getText();
        try {
            dicM.addWord(new_target_String, new_explain_String);
            message_lable.setText("Done!");
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }

        add_target_teaxfield.setText("");
        add_explain_textarea.setText("");

        add_dialog.setVisible(false);
        add_dialog.dispose();

        message_dialog.setLocationRelativeTo(null);
        message_dialog.setVisible(true);

    }//GEN-LAST:event_add_submit_buttonActionPerformed

    private void message_ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_message_ok_buttonActionPerformed
        message_dialog.setVisible(false);
        message_dialog.dispose();
    }//GEN-LAST:event_message_ok_buttonActionPerformed

    private void edit_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_submit_buttonActionPerformed

        String edit_targetString = tab2_target_textField.getText();
        String new_targetString = edit_target_teaxfield.getText();
        String new_explainString = edit_explain_textarea.getText();

        dicM.editWord(edit_targetString, new_targetString, new_explainString);

        edit_dialog.setVisible(false); //you can't see me!
        edit_dialog.dispose(); //Destroy the JFrame object

        message_dialog.setLocationRelativeTo(null);
        message_dialog.setVisible(true);

        //Hien len cai vua edit
        tab2_target_textField.setText(new_targetString);
        tab2_explain_textArea.setText(new_explainString);
        DefaultListModel model = new DefaultListModel();
        tab2_suggest_list.setModel(model);
    }//GEN-LAST:event_edit_submit_buttonActionPerformed

    private void tab2_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2_add_buttonActionPerformed
        add_dialog.setLocationRelativeTo(null);
        add_dialog.setVisible(true);        
        add_target_teaxfield.setText(tab2_target_textField.getText());
        add_explain_textarea.setText(tab2_explain_textArea.getText());
    }//GEN-LAST:event_tab2_add_buttonActionPerformed

    private void tab2_delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2_delete_buttonActionPerformed
        String check_explain_textArea = tab2_explain_textArea.getText();
        
        if (!check_explain_textArea.equals("")) {
        
            String deleteTarget = tab2_target_textField.getText();
            boolean check = dicM.deleteWord(deleteTarget);   
            
            message_lable.setText("Done!");
            message_dialog.setLocationRelativeTo(null);
            message_dialog.setVisible(true);

            //xoa tu vua xoa
            tab2_target_textField.setText("");
            tab2_explain_textArea.setText("");     

            DefaultListModel model = new DefaultListModel();             
            tab2_suggest_list.setModel(model);

        }
        else {
            message_lable.setText("Choose word to delete!");
            message_dialog.setLocationRelativeTo(null);
            message_dialog.setVisible(true);
            
        }
    }//GEN-LAST:event_tab2_delete_buttonActionPerformed

    private void tab2_edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2_edit_buttonActionPerformed
        String check_explain_textArea = tab2_explain_textArea.getText();
        
        if (!check_explain_textArea.equals("")) {        
            edit_dialog.setLocationRelativeTo(null);
            edit_dialog.setVisible(true);
            edit_target_teaxfield.setText(tab2_target_textField.getText());
            edit_explain_textarea.setText(tab2_explain_textArea.getText());
        } else {
            message_lable.setText("Choose word to edit!");
            message_dialog.setLocationRelativeTo(null);
            message_dialog.setVisible(true);            
        }
    }//GEN-LAST:event_tab2_edit_buttonActionPerformed

    private void tab1_target_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1_target_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab1_target_textFieldActionPerformed

    public void runApplication() {
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog add_dialog;
    private javax.swing.JTextArea add_explain_textarea;
    private javax.swing.JButton add_submit_button;
    private javax.swing.JTextField add_target_teaxfield;
    private javax.swing.JPanel content;
    private javax.swing.JDialog edit_dialog;
    private javax.swing.JTextArea edit_explain_textarea;
    private javax.swing.JPanel edit_panel;
    private javax.swing.JButton edit_submit_button;
    private javax.swing.JTextField edit_target_teaxfield;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel menuTab;
    private javax.swing.JPanel menu_tab1;
    private javax.swing.JPanel menu_tab2;
    private javax.swing.JPanel menu_tab3;
    private javax.swing.JPanel menu_tab4;
    private javax.swing.JDialog message_dialog;
    private javax.swing.JLabel message_lable;
    private javax.swing.JButton message_ok_button;
    private javax.swing.JPanel message_panel;
    private javax.swing.JPanel tab1;
    private javax.swing.JTextArea tab1_explain_textArea;
    private javax.swing.JButton tab1_speak_button;
    private javax.swing.JList<String> tab1_suggest_list;
    private javax.swing.JTextField tab1_target_textField;
    private javax.swing.JButton tab1_translate_button;
    private javax.swing.JPanel tab2;
    private javax.swing.JButton tab2_add_button;
    private javax.swing.JButton tab2_delete_button;
    private javax.swing.JButton tab2_edit_button;
    private javax.swing.JTextArea tab2_explain_textArea;
    private javax.swing.JButton tab2_speak_button;
    private javax.swing.JList<String> tab2_suggest_list;
    private javax.swing.JTextField tab2_target_textField;
    private javax.swing.JButton tab2_translate_button;
    private javax.swing.JPanel tab3;
    private javax.swing.JTextArea tab3_explain_textArea;
    private javax.swing.JComboBox<String> tab3_selected;
    private javax.swing.JTextArea tab3_target_textArea;
    private javax.swing.JButton tab3_translate_button;
    private javax.swing.JPanel tab4;
    // End of variables declaration//GEN-END:variables
}
